export class PlayerItem {
    constructor(
        public id: any,
        public name: any,
        public role: any,
        public someStuff: any,
        public otherStuff: any,
        public moreStuff1: any,
        public moreStuff2: any,
        public moreStuff3: any,
    ) { }
}


export const PlayerItems: PlayerItem[] = [
       { id: 1, name: "Ter Stegen", role: "Goalkeeper", someStuff: "Sed ut perspiciatis unde omnis iste natus error sit", otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. \n\nNeque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt \n\nut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil qiuiliae consequatur,\n\n vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?", moreStuff1: '*********some more stuff*******', moreStuff2: '*********some more stuff*******', moreStuff3: 'some more stuff' },

        { id: 3, name: "Piqué", role: "Defender", someStuff: "Sed ut perspiciatis unde omnis iste natus error sit ", otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. \n\nNeque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt \n\nut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil qiuiliae consequatur,\n\n vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?", moreStuff1: '*********some more stuff*******', moreStuff2: '*********some more stuff*******', moreStuff3: 'some more stuff'  },

        { id: 4, name: "I. Rakitic", role: "Midfielder", someStuff: "Sed ut perspiciatis unde omnis iste natus error sit", otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. \n\nNeque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt \n\nut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil qiuiliae consequatur,\n\n vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?" , moreStuff1: 'some more stuff', moreStuff2: 'some more stuff', moreStuff3: 'some more stuff'},
        
        { id: 5, name: "Sergio", role: "Midfielder", someStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.", otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. \n\nNeque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt \n\nut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil qiuiliae consequatur,\n\n vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?", moreStuff1: '*********some more stuff*******', moreStuff2: '*********some more stuff*******', moreStuff3: 'some more stuff' },

        { id: 6, name: "Denis Suárez", role: "Midfielder", someStuff: "Sed ut perspiciatis unde omnis iste natus error sit", otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. \n\nNeque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt \n\nut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil qiuiliae consequatur,\n\n vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?", moreStuff1: '*********some more stuff*******', moreStuff2: '*********some more stuff*******', moreStuff3: 'some more stuff'  },

        { id: 7, name: "Arda", role: "Midfielder", someStuff: "Sed ut perspiciatis unde omnis iste natus error sit", otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. \n\nNeque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt \n\nut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil qiuiliae consequatur,\n\n vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",moreStuff1: '*********some more stuff*******', moreStuff2: '*********some more stuff*******', moreStuff3: 'some more stuff' },

        { id: 8, name: "A. Iniesta", role: "Midfielder", someStuff: "Sed ut perspiciatis unde omnis iste natus error sit", otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. \n\nNeque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt \n\nut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil qiuiliae consequatur,\n\n vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?", moreStuff1: '*********some more stuff*******', moreStuff2: '*********some more stuff*******', moreStuff3: 'some more stuff'  },

        { id: 9, name: "Suárez", role: "Forward", someStuff: "Sed ut perspiciatis unde omnis iste natus error sit", otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. \n\nNeque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt \n\nut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil qiuiliae consequatur,\n\n vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?" , moreStuff1: '*********some more stuff*******', moreStuff2: '*********some more stuff*******', moreStuff3: 'some more stuff' },

        { id: 10, name: "Messi", role: "Forward", someStuff: "Sed ut perspiciatis unde omnis iste natus error sit.", otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. \n\nNeque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt \n\nut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil qiuiliae consequatur,\n\n vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?", moreStuff1: '*********some more stuff*******', moreStuff2: '*********some more stuff*******', moreStuff3: 'some more stuff'  },

        { id: 11, name: "Neymar", role: "Forward", someStuff: "Sed ut perspiciatis unde omnis iste natus error sit", otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. \n\nNeque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt \n\nut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil qiuiliae consequatur,\n\n vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?", moreStuff1: '*********some more stuff*******', moreStuff2: '*********some more stuff*******', moreStuff3: 'some more stuff'  },

        { id: 12, name: "Rafinha", role: "Midfielder", someStuff: "Sed ut perspiciatis unde omnis iste natus error sit", otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. \n\nNeque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt \n\nut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil qiuiliae consequatur,\n\n vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?", moreStuff1: '*********some more stuff*******', moreStuff2: '*********some more stuff*******', moreStuff3: 'some more stuff'  },

        { id: 13, name: "Cillessen", role: "Goalkeeper", someStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.", otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. \n\nNeque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt \n\nut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil qiuiliae consequatur,\n\n vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?" , moreStuff1: '*********some more stuff*******', moreStuff2: '*********some more stuff*******', moreStuff3: 'some more stuff' },

        { id: 14, name: "Mascherano", role: "Defender", someStuff: "Sed ut perspiciatis unde omnis iste natus error sit", otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. \n\nNeque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt \n\nut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil qiuiliae consequatur,\n\n vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?", moreStuff1: '*********some more stuff*******', moreStuff2: '*********some more stuff*******', moreStuff3: 'some more stuff' },


]