export class PlayerItem2 {
    constructor(
        public id: any,
        public name: any,
        public role: any,
        public someStuff: any,
        public otherStuff: any,
        public moreStuff1: any,
        public moreStuff2: any,
    ) { }
}

export const PlayerItems2: PlayerItem2[] = [ /**this data has more variety than PlayerItems. Specifically, the "someStuff" item varies here. There, it stays the same.***/
    {
        id: 1,
        name: "Ter Stegen ",
        role: "Goalkeeper",
        someStuff: "sgst wt jsgjs gsg wtsfajaogj jjojojgojgo jwg ",
        otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. ",
        moreStuff1: '*********some more stuff*******',
        moreStuff2: '*********some more stuff*******',
    },
    {
        id: 2,
        name: "Piqué ",
        role: "Defender ",
        someStuff: "wowewn nviwvjwigjwgiwg wg wgiwngiwjijwijjw wg wg wg wgwg wgwg wgwgregeb e etheh eheth ethehe h wgwgqgqg g rehen eh eheh eh eh eh eh",
        otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. \n\n",
        moreStuff1: '*********some more stuff*******',
        moreStuff2: '*********some more stuff*******',
  
    },
    {
        id: 3,
        name: "I. Rakitic ",
        role: "Midfielder",
        someStuff: "pwoerwpwkjw wpwfwkfp wf kppp[wp[[pw fsgsg gwgwwgw wwgw gwg wg wg w gwg ",
        otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
        moreStuff1: '*********some more stuff*******',
        moreStuff2: '*********some more stuff*******',
    },
    {
        id: 4,
        name: "Sergio ",
        role: "Midfielder",
        someStuff: "snvsnvwignwnv vv e vwv nwiv nwvwv nwv iwnv winginwgiwrntornowinwriywrnywnrbb ebnebenb ibe nebi enb eb ieniwng",
        otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. ",
        moreStuff1: '*********some more stuff*******',
        moreStuff2: '*********some more stuff*******',
    },
    {
        id: 5,
        name: "Denis Suárez ",
        role: "Midfielder",
        someStuff: "pwrwrw w pwg wg wgwg ejheoh g jwg wogjwgjwrg wwg wgs gdsg dgwgwrgw",
        otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
        moreStuff1: '*********some more stuff*******',
        moreStuff2: '*********some more stuff*******',
    },
    {
        id: 6,
        name: "Arda ",
        role: "Midfielder",
        someStuff: "g wg wg grgrgrwgwgwgwrg wgwrgwg wg wgwrrgwgwg",
        otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
        moreStuff1: '*********some more stuff*******',
        moreStuff2: '*********some more stuff*******',
    },
    {
        id: 7,
        name: "A. Iniesta ",
        role: "Midfielder",
        someStuff: "wgwigwnn wivwghwgiwgwngv wgwgwgnwgiwgwghwigwng wg wg ",
        otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
        moreStuff1: '*********some more stuff*******',
        moreStuff2: '*********some more stuff*******',
    },
    {
        id: 8,
        name: "Suárez ",
        role: "Forward",
        someStuff: "wewrworwrwe ogwjgo wjojeorwjrowjrw wgpwporporpor wgwg phoaka ggk alfk kwglsgksglksglkg sgg",
        otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
        moreStuff1: '*********some more stuff*******',
        moreStuff2: '*********some more stuff*******',
    },
    {
        id: 9,
        name: "Messi ",
        role: "Forward",
        someStuff: "wrpwrwpowgjwg wg wg wgwgwmsacmcomvnvnnfvsngksnvnshsgns   snv snv sv ns vsk g snsg sng sng msg nsg nsgjsgn sg ",
        otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
        moreStuff1: '*********some more stuff*******',
        moreStuff2: '*********some more stuff*******',
    },
    {
        id: 10,
        name: "Neymar ",
        role: "Forward",
        someStuff: "wfwvwb wbwj biwbn nks mclmscosckwpcwkcemnvbnebneb ebnebi enbeboepr  e bebebeobneobnepw pe",
        otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem",
        moreStuff1: '*********some more stuff*******',
        moreStuff2: '*********some more stuff*******',
    },
    {
        id: 11,
        name: "Rafinha ",
        role: "Midfielder",
        someStuff: "adaa faf nad=adj gwog jwgowjg wog wjgow jwog jwgow vnvwihgwifholwje n wf wjfj jnw nmmlmw ",
        otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa qu",
        moreStuff1: '*********some more stuff*******',
        moreStuff2: '*********some more stuff*******',
    },
    {
        id: 12,
        name: "Cillessen ",
        role: "Goalkeeper",
        someStuff: "wotuwng nwgi hwg nwvnvnrgo wp pwowfw nw mwcowcmwocmw cmwvnwgnwign wgn wgw  fwpf wj wjfwofjwje",
        otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. \n\nNeque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi ",
        moreStuff1: '*********some more stuff*******',
        moreStuff2: '*********some more stuff*******',
    },
      {
        id: 1,
        name: "Ter Stegen ",
        role: "Goalkeeper",
        someStuff: "sgst wt jsgjs gsg wtsfajaogj jjojojgojgo jwg ",
        otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. ",
        moreStuff1: '*********some more stuff*******',
        moreStuff2: '*********some more stuff*******',
    },
    {
        id: 2,
        name: "Piqué ",
        role: "Defender ",
        someStuff: "wowewn nviwvjwigjwgiwg wg wgiwngiwjijwijjw wg wg wg wgwg wgwg wgwgregeb e etheh eheth ethehe h wgwgqgqg g rehen eh eheh eh eh eh eh",
        otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. \n\n",
        moreStuff1: '*********some more stuff*******',
        moreStuff2: '*********some more stuff*******',
  
    },
    {
        id: 3,
        name: "I. Rakitic ",
        role: "Midfielder",
        someStuff: "pwoerwpwkjw wpwfwkfp wf kppp[wp[[pw fsgsg gwgwwgw wwgw gwg wg wg w gwg ",
        otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
        moreStuff1: '*********some more stuff*******',
        moreStuff2: '*********some more stuff*******',
    },
    {
        id: 4,
        name: "Sergio ",
        role: "Midfielder",
        someStuff: "snvsnvwignwnv vv e vwv nwiv nwvwv nwv iwnv winginwgiwrntornowinwriywrnywnrbb ebnebenb ibe nebi enb eb ieniwng",
        otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. ",
        moreStuff1: '*********some more stuff*******',
        moreStuff2: '*********some more stuff*******',
    },
    {
        id: 5,
        name: "Denis Suárez ",
        role: "Midfielder",
        someStuff: "pwrwrw w pwg wg wgwg ejheoh g jwg wogjwgjwrg wwg wgs gdsg dgwgwrgw",
        otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
        moreStuff1: '*********some more stuff*******',
        moreStuff2: '*********some more stuff*******',
    },
    {
        id: 6,
        name: "Arda ",
        role: "Midfielder",
        someStuff: "g wg wg grgrgrwgwgwgwrg wgwrgwg wg wgwrrgwgwg",
        otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
        moreStuff1: '*********some more stuff*******',
        moreStuff2: '*********some more stuff*******',
    },
    {
        id: 7,
        name: "A. Iniesta ",
        role: "Midfielder",
        someStuff: "wgwigwnn wivwghwgiwgwngv wgwgwgnwgiwgwghwigwng wg wg ",
        otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
        moreStuff1: '*********some more stuff*******',
        moreStuff2: '*********some more stuff*******',
    },
    {
        id: 8,
        name: "Suárez ",
        role: "Forward",
        someStuff: "wewrworwrwe ogwjgo wjojeorwjrowjrw wgpwporporpor wgwg phoaka ggk alfk kwglsgksglksglkg sgg",
        otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
        moreStuff1: '*********some more stuff*******',
        moreStuff2: '*********some more stuff*******',
    },
    {
        id: 9,
        name: "Messi ",
        role: "Forward",
        someStuff: "wrpwrwpowgjwg wg wg wgwgwmsacmcomvnvnnfvsngksnvnshsgns   snv snv sv ns vsk g snsg sng sng msg nsg nsgjsgn sg ",
        otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
        moreStuff1: '*********some more stuff*******',
        moreStuff2: '*********some more stuff*******',
    },
    {
        id: 10,
        name: "Neymar ",
        role: "Forward",
        someStuff: "wfwvwb wbwj biwbn nks mclmscosckwpcwkcemnvbnebneb ebnebi enbeboepr  e bebebeobneobnepw pe",
        otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem",
        moreStuff1: '*********some more stuff*******',
        moreStuff2: '*********some more stuff*******',
    },
    {
        id: 11,
        name: "Rafinha ",
        role: "Midfielder",
        someStuff: "adaa faf nad=adj gwog jwgowjg wog wjgow jwog jwgow vnvwihgwifholwje n wf wjfj jnw nmmlmw ",
        otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa qu",
        moreStuff1: '*********some more stuff*******',
        moreStuff2: '*********some more stuff*******',
    },
    {
        id: 12,
        name: "Cillessen ",
        role: "Goalkeeper",
        someStuff: "wotuwng nwgi hwg nwvnvnrgo wp pwowfw nw mwcowcmwocmw cmwvnwgnwign wgn wgw  fwpf wj wjfwofjwje",
        otherStuff: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. \n\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. \n\nNeque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi ",
        moreStuff1: '*********some more stuff*******',
        moreStuff2: '*********some more stuff*******',
    },
]